/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as test from "./test";
export type { test };
export type { PauserSet } from "./PauserSet";
export type { PrivateTaxiDispatch } from "./PrivateTaxiDispatch";
export type { TaxiGateway } from "./TaxiGateway";
