/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace PrivateTaxiDispatch {
  export type EncryptedLocationStruct = {
    latitude: BytesLike;
    longitude: BytesLike;
    isActive: boolean;
  };

  export type EncryptedLocationStructOutput = [
    latitude: string,
    longitude: string,
    isActive: boolean
  ] & { latitude: string; longitude: string; isActive: boolean };
}

export interface PrivateTaxiDispatchInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "acceptOffer"
      | "cancelRequest"
      | "completeRide"
      | "dispatcher"
      | "driverCounter"
      | "driverHistory"
      | "drivers"
      | "emergencyPause"
      | "gateway"
      | "getDriverHistory"
      | "getDriverInfo"
      | "getGatewayAddress"
      | "getPassengerHistory"
      | "getRequestInfo"
      | "getSystemStats"
      | "isDriverAvailable"
      | "isDriverEligibleForOffer"
      | "isRegisteredDriver"
      | "isRequestActive"
      | "isRequestCancellable"
      | "isSystemOperational"
      | "passengerHistory"
      | "protocolId"
      | "registerDriver"
      | "requestCounter"
      | "requestOffers"
      | "requestRide"
      | "requests"
      | "setAvailability"
      | "setGateway"
      | "submitOffer"
      | "updateLocation"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DriverRegistered"
      | "LocationUpdated"
      | "OfferSubmitted"
      | "RideCancelled"
      | "RideCompleted"
      | "RideMatched"
      | "RideRequested"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "acceptOffer",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelRequest",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "completeRide",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "dispatcher",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "driverCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "driverHistory",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "drivers",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyPause",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "gateway", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getDriverHistory",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getDriverInfo",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getGatewayAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPassengerHistory",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRequestInfo",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getSystemStats",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isDriverAvailable",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isDriverEligibleForOffer",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isRegisteredDriver",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isRequestActive",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isRequestCancellable",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isSystemOperational",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "passengerHistory",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "protocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "registerDriver",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requestCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requestOffers",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "requestRide",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "requests",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setAvailability",
    values: [boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setGateway",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitOffer",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateLocation",
    values: [BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "acceptOffer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelRequest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "completeRide",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "dispatcher", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "driverCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "driverHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "drivers", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "emergencyPause",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "gateway", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getDriverHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDriverInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getGatewayAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPassengerHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRequestInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSystemStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isDriverAvailable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isDriverEligibleForOffer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isRegisteredDriver",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isRequestActive",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isRequestCancellable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isSystemOperational",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "passengerHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "protocolId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerDriver",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestOffers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestRide",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "requests", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setAvailability",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setGateway", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "submitOffer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateLocation",
    data: BytesLike
  ): Result;
}

export namespace DriverRegisteredEvent {
  export type InputTuple = [driver: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [driver: string, timestamp: bigint];
  export interface OutputObject {
    driver: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LocationUpdatedEvent {
  export type InputTuple = [driver: AddressLike];
  export type OutputTuple = [driver: string];
  export interface OutputObject {
    driver: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OfferSubmittedEvent {
  export type InputTuple = [requestId: BigNumberish, driver: AddressLike];
  export type OutputTuple = [requestId: bigint, driver: string];
  export interface OutputObject {
    requestId: bigint;
    driver: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RideCancelledEvent {
  export type InputTuple = [requestId: BigNumberish, passenger: AddressLike];
  export type OutputTuple = [requestId: bigint, passenger: string];
  export interface OutputObject {
    requestId: bigint;
    passenger: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RideCompletedEvent {
  export type InputTuple = [
    requestId: BigNumberish,
    driver: AddressLike,
    passenger: AddressLike
  ];
  export type OutputTuple = [
    requestId: bigint,
    driver: string,
    passenger: string
  ];
  export interface OutputObject {
    requestId: bigint;
    driver: string;
    passenger: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RideMatchedEvent {
  export type InputTuple = [
    requestId: BigNumberish,
    driver: AddressLike,
    passenger: AddressLike
  ];
  export type OutputTuple = [
    requestId: bigint,
    driver: string,
    passenger: string
  ];
  export interface OutputObject {
    requestId: bigint;
    driver: string;
    passenger: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RideRequestedEvent {
  export type InputTuple = [requestId: BigNumberish, passenger: AddressLike];
  export type OutputTuple = [requestId: bigint, passenger: string];
  export interface OutputObject {
    requestId: bigint;
    passenger: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PrivateTaxiDispatch extends BaseContract {
  connect(runner?: ContractRunner | null): PrivateTaxiDispatch;
  waitForDeployment(): Promise<this>;

  interface: PrivateTaxiDispatchInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  acceptOffer: TypedContractMethod<
    [_requestId: BigNumberish, _offerIndex: BigNumberish],
    [void],
    "nonpayable"
  >;

  cancelRequest: TypedContractMethod<
    [_requestId: BigNumberish],
    [void],
    "nonpayable"
  >;

  completeRide: TypedContractMethod<
    [_requestId: BigNumberish, _passengerRating: BigNumberish],
    [void],
    "nonpayable"
  >;

  dispatcher: TypedContractMethod<[], [string], "view">;

  driverCounter: TypedContractMethod<[], [bigint], "view">;

  driverHistory: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  drivers: TypedContractMethod<
    [arg0: AddressLike],
    [
      [
        string,
        PrivateTaxiDispatch.EncryptedLocationStructOutput,
        string,
        boolean,
        boolean,
        bigint,
        bigint
      ] & {
        driverAddress: string;
        currentLocation: PrivateTaxiDispatch.EncryptedLocationStructOutput;
        rating: string;
        isAvailable: boolean;
        isRegistered: boolean;
        totalRides: bigint;
        registrationTime: bigint;
      }
    ],
    "view"
  >;

  emergencyPause: TypedContractMethod<[], [void], "nonpayable">;

  gateway: TypedContractMethod<[], [string], "view">;

  getDriverHistory: TypedContractMethod<
    [_driver: AddressLike],
    [bigint[]],
    "view"
  >;

  getDriverInfo: TypedContractMethod<
    [_driver: AddressLike],
    [
      [boolean, boolean, bigint, bigint] & {
        isRegistered: boolean;
        isAvailable: boolean;
        totalRides: bigint;
        registrationTime: bigint;
      }
    ],
    "view"
  >;

  getGatewayAddress: TypedContractMethod<[], [string], "view">;

  getPassengerHistory: TypedContractMethod<
    [_passenger: AddressLike],
    [bigint[]],
    "view"
  >;

  getRequestInfo: TypedContractMethod<
    [_requestId: BigNumberish],
    [
      [string, string, boolean, boolean, bigint, bigint] & {
        passenger: string;
        assignedDriver: string;
        isCompleted: boolean;
        isCancelled: boolean;
        requestTime: bigint;
        offerCount: bigint;
      }
    ],
    "view"
  >;

  getSystemStats: TypedContractMethod<
    [],
    [[bigint, bigint] & { totalRequests: bigint; totalDrivers: bigint }],
    "view"
  >;

  isDriverAvailable: TypedContractMethod<
    [_driverAddress: AddressLike],
    [boolean],
    "view"
  >;

  isDriverEligibleForOffer: TypedContractMethod<
    [_driverAddress: AddressLike, _requestId: BigNumberish],
    [boolean],
    "view"
  >;

  isRegisteredDriver: TypedContractMethod<
    [_address: AddressLike],
    [boolean],
    "view"
  >;

  isRequestActive: TypedContractMethod<
    [_requestId: BigNumberish],
    [boolean],
    "view"
  >;

  isRequestCancellable: TypedContractMethod<
    [_passengerAddress: AddressLike, _requestId: BigNumberish],
    [boolean],
    "view"
  >;

  isSystemOperational: TypedContractMethod<[], [boolean], "view">;

  passengerHistory: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  protocolId: TypedContractMethod<[], [bigint], "view">;

  registerDriver: TypedContractMethod<[], [void], "nonpayable">;

  requestCounter: TypedContractMethod<[], [bigint], "view">;

  requestOffers: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [bigint, string, string, string, boolean, bigint] & {
        requestId: bigint;
        driver: string;
        proposedFare: string;
        estimatedTime: string;
        isAccepted: boolean;
        offerTime: bigint;
      }
    ],
    "view"
  >;

  requestRide: TypedContractMethod<
    [
      _pickupLat: BigNumberish,
      _pickupLng: BigNumberish,
      _destLat: BigNumberish,
      _destLng: BigNumberish,
      _maxFare: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  requests: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        PrivateTaxiDispatch.EncryptedLocationStructOutput,
        PrivateTaxiDispatch.EncryptedLocationStructOutput,
        string,
        string,
        boolean,
        boolean,
        bigint,
        bigint
      ] & {
        passenger: string;
        pickupLocation: PrivateTaxiDispatch.EncryptedLocationStructOutput;
        destination: PrivateTaxiDispatch.EncryptedLocationStructOutput;
        maxFare: string;
        assignedDriver: string;
        isCompleted: boolean;
        isCancelled: boolean;
        requestTime: bigint;
        completionTime: bigint;
      }
    ],
    "view"
  >;

  setAvailability: TypedContractMethod<
    [_available: boolean],
    [void],
    "nonpayable"
  >;

  setGateway: TypedContractMethod<
    [_gatewayAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  submitOffer: TypedContractMethod<
    [
      _requestId: BigNumberish,
      _proposedFare: BigNumberish,
      _estimatedTime: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  updateLocation: TypedContractMethod<
    [_latitude: BigNumberish, _longitude: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "acceptOffer"
  ): TypedContractMethod<
    [_requestId: BigNumberish, _offerIndex: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "cancelRequest"
  ): TypedContractMethod<[_requestId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "completeRide"
  ): TypedContractMethod<
    [_requestId: BigNumberish, _passengerRating: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "dispatcher"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "driverCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "driverHistory"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "drivers"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [
        string,
        PrivateTaxiDispatch.EncryptedLocationStructOutput,
        string,
        boolean,
        boolean,
        bigint,
        bigint
      ] & {
        driverAddress: string;
        currentLocation: PrivateTaxiDispatch.EncryptedLocationStructOutput;
        rating: string;
        isAvailable: boolean;
        isRegistered: boolean;
        totalRides: bigint;
        registrationTime: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "emergencyPause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "gateway"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getDriverHistory"
  ): TypedContractMethod<[_driver: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getDriverInfo"
  ): TypedContractMethod<
    [_driver: AddressLike],
    [
      [boolean, boolean, bigint, bigint] & {
        isRegistered: boolean;
        isAvailable: boolean;
        totalRides: bigint;
        registrationTime: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getGatewayAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getPassengerHistory"
  ): TypedContractMethod<[_passenger: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getRequestInfo"
  ): TypedContractMethod<
    [_requestId: BigNumberish],
    [
      [string, string, boolean, boolean, bigint, bigint] & {
        passenger: string;
        assignedDriver: string;
        isCompleted: boolean;
        isCancelled: boolean;
        requestTime: bigint;
        offerCount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getSystemStats"
  ): TypedContractMethod<
    [],
    [[bigint, bigint] & { totalRequests: bigint; totalDrivers: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "isDriverAvailable"
  ): TypedContractMethod<[_driverAddress: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isDriverEligibleForOffer"
  ): TypedContractMethod<
    [_driverAddress: AddressLike, _requestId: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isRegisteredDriver"
  ): TypedContractMethod<[_address: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isRequestActive"
  ): TypedContractMethod<[_requestId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "isRequestCancellable"
  ): TypedContractMethod<
    [_passengerAddress: AddressLike, _requestId: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isSystemOperational"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "passengerHistory"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "protocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "registerDriver"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "requestCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "requestOffers"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [bigint, string, string, string, boolean, bigint] & {
        requestId: bigint;
        driver: string;
        proposedFare: string;
        estimatedTime: string;
        isAccepted: boolean;
        offerTime: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "requestRide"
  ): TypedContractMethod<
    [
      _pickupLat: BigNumberish,
      _pickupLng: BigNumberish,
      _destLat: BigNumberish,
      _destLng: BigNumberish,
      _maxFare: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "requests"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        PrivateTaxiDispatch.EncryptedLocationStructOutput,
        PrivateTaxiDispatch.EncryptedLocationStructOutput,
        string,
        string,
        boolean,
        boolean,
        bigint,
        bigint
      ] & {
        passenger: string;
        pickupLocation: PrivateTaxiDispatch.EncryptedLocationStructOutput;
        destination: PrivateTaxiDispatch.EncryptedLocationStructOutput;
        maxFare: string;
        assignedDriver: string;
        isCompleted: boolean;
        isCancelled: boolean;
        requestTime: bigint;
        completionTime: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "setAvailability"
  ): TypedContractMethod<[_available: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setGateway"
  ): TypedContractMethod<[_gatewayAddress: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "submitOffer"
  ): TypedContractMethod<
    [
      _requestId: BigNumberish,
      _proposedFare: BigNumberish,
      _estimatedTime: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateLocation"
  ): TypedContractMethod<
    [_latitude: BigNumberish, _longitude: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "DriverRegistered"
  ): TypedContractEvent<
    DriverRegisteredEvent.InputTuple,
    DriverRegisteredEvent.OutputTuple,
    DriverRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "LocationUpdated"
  ): TypedContractEvent<
    LocationUpdatedEvent.InputTuple,
    LocationUpdatedEvent.OutputTuple,
    LocationUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OfferSubmitted"
  ): TypedContractEvent<
    OfferSubmittedEvent.InputTuple,
    OfferSubmittedEvent.OutputTuple,
    OfferSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "RideCancelled"
  ): TypedContractEvent<
    RideCancelledEvent.InputTuple,
    RideCancelledEvent.OutputTuple,
    RideCancelledEvent.OutputObject
  >;
  getEvent(
    key: "RideCompleted"
  ): TypedContractEvent<
    RideCompletedEvent.InputTuple,
    RideCompletedEvent.OutputTuple,
    RideCompletedEvent.OutputObject
  >;
  getEvent(
    key: "RideMatched"
  ): TypedContractEvent<
    RideMatchedEvent.InputTuple,
    RideMatchedEvent.OutputTuple,
    RideMatchedEvent.OutputObject
  >;
  getEvent(
    key: "RideRequested"
  ): TypedContractEvent<
    RideRequestedEvent.InputTuple,
    RideRequestedEvent.OutputTuple,
    RideRequestedEvent.OutputObject
  >;

  filters: {
    "DriverRegistered(address,uint256)": TypedContractEvent<
      DriverRegisteredEvent.InputTuple,
      DriverRegisteredEvent.OutputTuple,
      DriverRegisteredEvent.OutputObject
    >;
    DriverRegistered: TypedContractEvent<
      DriverRegisteredEvent.InputTuple,
      DriverRegisteredEvent.OutputTuple,
      DriverRegisteredEvent.OutputObject
    >;

    "LocationUpdated(address)": TypedContractEvent<
      LocationUpdatedEvent.InputTuple,
      LocationUpdatedEvent.OutputTuple,
      LocationUpdatedEvent.OutputObject
    >;
    LocationUpdated: TypedContractEvent<
      LocationUpdatedEvent.InputTuple,
      LocationUpdatedEvent.OutputTuple,
      LocationUpdatedEvent.OutputObject
    >;

    "OfferSubmitted(uint32,address)": TypedContractEvent<
      OfferSubmittedEvent.InputTuple,
      OfferSubmittedEvent.OutputTuple,
      OfferSubmittedEvent.OutputObject
    >;
    OfferSubmitted: TypedContractEvent<
      OfferSubmittedEvent.InputTuple,
      OfferSubmittedEvent.OutputTuple,
      OfferSubmittedEvent.OutputObject
    >;

    "RideCancelled(uint32,address)": TypedContractEvent<
      RideCancelledEvent.InputTuple,
      RideCancelledEvent.OutputTuple,
      RideCancelledEvent.OutputObject
    >;
    RideCancelled: TypedContractEvent<
      RideCancelledEvent.InputTuple,
      RideCancelledEvent.OutputTuple,
      RideCancelledEvent.OutputObject
    >;

    "RideCompleted(uint32,address,address)": TypedContractEvent<
      RideCompletedEvent.InputTuple,
      RideCompletedEvent.OutputTuple,
      RideCompletedEvent.OutputObject
    >;
    RideCompleted: TypedContractEvent<
      RideCompletedEvent.InputTuple,
      RideCompletedEvent.OutputTuple,
      RideCompletedEvent.OutputObject
    >;

    "RideMatched(uint32,address,address)": TypedContractEvent<
      RideMatchedEvent.InputTuple,
      RideMatchedEvent.OutputTuple,
      RideMatchedEvent.OutputObject
    >;
    RideMatched: TypedContractEvent<
      RideMatchedEvent.InputTuple,
      RideMatchedEvent.OutputTuple,
      RideMatchedEvent.OutputObject
    >;

    "RideRequested(uint32,address)": TypedContractEvent<
      RideRequestedEvent.InputTuple,
      RideRequestedEvent.OutputTuple,
      RideRequestedEvent.OutputObject
    >;
    RideRequested: TypedContractEvent<
      RideRequestedEvent.InputTuple,
      RideRequestedEvent.OutputTuple,
      RideRequestedEvent.OutputObject
    >;
  };
}
