/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface TaxiGatewayInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "callKMSGeneration"
      | "decryptionContract"
      | "getGatewayStatus"
      | "getPauserCount"
      | "isKMSGenerationConfigured"
      | "isOperational"
      | "isPauseAuthorized"
      | "isPublicDecryptAllowed"
      | "kmsGenerationContract"
      | "owner"
      | "pause"
      | "paused"
      | "pauserSet"
      | "requestDecryption"
      | "setDecryptionContract"
      | "unpause"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DecryptionCompleted"
      | "DecryptionRequested"
      | "KMSGenerationCalled"
      | "Paused"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "callKMSGeneration",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "decryptionContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getGatewayStatus",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPauserCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isKMSGenerationConfigured",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isOperational",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isPauseAuthorized",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isPublicDecryptAllowed",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "kmsGenerationContract",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(functionFragment: "pauserSet", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "requestDecryption",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setDecryptionContract",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "callKMSGeneration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "decryptionContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getGatewayStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPauserCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isKMSGenerationConfigured",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isOperational",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isPauseAuthorized",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isPublicDecryptAllowed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "kmsGenerationContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pauserSet", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "requestDecryption",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDecryptionContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
}

export namespace DecryptionCompletedEvent {
  export type InputTuple = [requestId: BigNumberish, result: BytesLike];
  export type OutputTuple = [requestId: bigint, result: string];
  export interface OutputObject {
    requestId: bigint;
    result: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DecryptionRequestedEvent {
  export type InputTuple = [requestId: BigNumberish, requester: AddressLike];
  export type OutputTuple = [requestId: bigint, requester: string];
  export interface OutputObject {
    requestId: bigint;
    requester: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace KMSGenerationCalledEvent {
  export type InputTuple = [caller: AddressLike, data: BytesLike];
  export type OutputTuple = [caller: string, data: string];
  export interface OutputObject {
    caller: string;
    data: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [pauser: AddressLike];
  export type OutputTuple = [pauser: string];
  export interface OutputObject {
    pauser: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [owner: AddressLike];
  export type OutputTuple = [owner: string];
  export interface OutputObject {
    owner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TaxiGateway extends BaseContract {
  connect(runner?: ContractRunner | null): TaxiGateway;
  waitForDeployment(): Promise<this>;

  interface: TaxiGatewayInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  callKMSGeneration: TypedContractMethod<
    [_data: BytesLike],
    [string],
    "nonpayable"
  >;

  decryptionContract: TypedContractMethod<[], [string], "view">;

  getGatewayStatus: TypedContractMethod<
    [],
    [
      [boolean, bigint, boolean, boolean] & {
        isPaused: boolean;
        pauserCount: bigint;
        kmsConfigured: boolean;
        decryptionConfigured: boolean;
      }
    ],
    "view"
  >;

  getPauserCount: TypedContractMethod<[], [bigint], "view">;

  isKMSGenerationConfigured: TypedContractMethod<[], [boolean], "view">;

  isOperational: TypedContractMethod<[], [boolean], "view">;

  isPauseAuthorized: TypedContractMethod<
    [_address: AddressLike],
    [boolean],
    "view"
  >;

  isPublicDecryptAllowed: TypedContractMethod<
    [_requester: AddressLike],
    [boolean],
    "view"
  >;

  kmsGenerationContract: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  pauserSet: TypedContractMethod<[], [string], "view">;

  requestDecryption: TypedContractMethod<
    [_ciphertext: BytesLike],
    [bigint],
    "nonpayable"
  >;

  setDecryptionContract: TypedContractMethod<
    [_decryptionContract: AddressLike],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "callKMSGeneration"
  ): TypedContractMethod<[_data: BytesLike], [string], "nonpayable">;
  getFunction(
    nameOrSignature: "decryptionContract"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getGatewayStatus"
  ): TypedContractMethod<
    [],
    [
      [boolean, bigint, boolean, boolean] & {
        isPaused: boolean;
        pauserCount: bigint;
        kmsConfigured: boolean;
        decryptionConfigured: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPauserCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "isKMSGenerationConfigured"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "isOperational"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "isPauseAuthorized"
  ): TypedContractMethod<[_address: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isPublicDecryptAllowed"
  ): TypedContractMethod<[_requester: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "kmsGenerationContract"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "pauserSet"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "requestDecryption"
  ): TypedContractMethod<[_ciphertext: BytesLike], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "setDecryptionContract"
  ): TypedContractMethod<
    [_decryptionContract: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "DecryptionCompleted"
  ): TypedContractEvent<
    DecryptionCompletedEvent.InputTuple,
    DecryptionCompletedEvent.OutputTuple,
    DecryptionCompletedEvent.OutputObject
  >;
  getEvent(
    key: "DecryptionRequested"
  ): TypedContractEvent<
    DecryptionRequestedEvent.InputTuple,
    DecryptionRequestedEvent.OutputTuple,
    DecryptionRequestedEvent.OutputObject
  >;
  getEvent(
    key: "KMSGenerationCalled"
  ): TypedContractEvent<
    KMSGenerationCalledEvent.InputTuple,
    KMSGenerationCalledEvent.OutputTuple,
    KMSGenerationCalledEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "DecryptionCompleted(uint256,bytes)": TypedContractEvent<
      DecryptionCompletedEvent.InputTuple,
      DecryptionCompletedEvent.OutputTuple,
      DecryptionCompletedEvent.OutputObject
    >;
    DecryptionCompleted: TypedContractEvent<
      DecryptionCompletedEvent.InputTuple,
      DecryptionCompletedEvent.OutputTuple,
      DecryptionCompletedEvent.OutputObject
    >;

    "DecryptionRequested(uint256,address)": TypedContractEvent<
      DecryptionRequestedEvent.InputTuple,
      DecryptionRequestedEvent.OutputTuple,
      DecryptionRequestedEvent.OutputObject
    >;
    DecryptionRequested: TypedContractEvent<
      DecryptionRequestedEvent.InputTuple,
      DecryptionRequestedEvent.OutputTuple,
      DecryptionRequestedEvent.OutputObject
    >;

    "KMSGenerationCalled(address,bytes)": TypedContractEvent<
      KMSGenerationCalledEvent.InputTuple,
      KMSGenerationCalledEvent.OutputTuple,
      KMSGenerationCalledEvent.OutputObject
    >;
    KMSGenerationCalled: TypedContractEvent<
      KMSGenerationCalledEvent.InputTuple,
      KMSGenerationCalledEvent.OutputTuple,
      KMSGenerationCalledEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
