/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface MockDecryptionInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "isRequestProcessed"
      | "processDecryption"
      | "processedRequests"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "DecryptionProcessed"): EventFragment;

  encodeFunctionData(
    functionFragment: "isRequestProcessed",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "processDecryption",
    values: [BigNumberish, BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "processedRequests",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "isRequestProcessed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "processDecryption",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "processedRequests",
    data: BytesLike
  ): Result;
}

export namespace DecryptionProcessedEvent {
  export type InputTuple = [
    requestId: BigNumberish,
    ciphertext: BytesLike,
    requester: AddressLike
  ];
  export type OutputTuple = [
    requestId: bigint,
    ciphertext: string,
    requester: string
  ];
  export interface OutputObject {
    requestId: bigint;
    ciphertext: string;
    requester: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MockDecryption extends BaseContract {
  connect(runner?: ContractRunner | null): MockDecryption;
  waitForDeployment(): Promise<this>;

  interface: MockDecryptionInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  isRequestProcessed: TypedContractMethod<
    [_requestId: BigNumberish],
    [boolean],
    "view"
  >;

  processDecryption: TypedContractMethod<
    [_requestId: BigNumberish, _ciphertext: BytesLike, _requester: AddressLike],
    [boolean],
    "nonpayable"
  >;

  processedRequests: TypedContractMethod<
    [arg0: BigNumberish],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "isRequestProcessed"
  ): TypedContractMethod<[_requestId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "processDecryption"
  ): TypedContractMethod<
    [_requestId: BigNumberish, _ciphertext: BytesLike, _requester: AddressLike],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "processedRequests"
  ): TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;

  getEvent(
    key: "DecryptionProcessed"
  ): TypedContractEvent<
    DecryptionProcessedEvent.InputTuple,
    DecryptionProcessedEvent.OutputTuple,
    DecryptionProcessedEvent.OutputObject
  >;

  filters: {
    "DecryptionProcessed(uint256,bytes,address)": TypedContractEvent<
      DecryptionProcessedEvent.InputTuple,
      DecryptionProcessedEvent.OutputTuple,
      DecryptionProcessedEvent.OutputObject
    >;
    DecryptionProcessed: TypedContractEvent<
      DecryptionProcessedEvent.InputTuple,
      DecryptionProcessedEvent.OutputTuple,
      DecryptionProcessedEvent.OutputObject
    >;
  };
}
