/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface MockKMSGenerationInterface extends Interface {
  getFunction(nameOrSignature: "generateKeys"): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "KMSCalled"): EventFragment;

  encodeFunctionData(
    functionFragment: "generateKeys",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "generateKeys",
    data: BytesLike
  ): Result;
}

export namespace KMSCalledEvent {
  export type InputTuple = [caller: AddressLike, data: BytesLike];
  export type OutputTuple = [caller: string, data: string];
  export interface OutputObject {
    caller: string;
    data: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MockKMSGeneration extends BaseContract {
  connect(runner?: ContractRunner | null): MockKMSGeneration;
  waitForDeployment(): Promise<this>;

  interface: MockKMSGenerationInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  generateKeys: TypedContractMethod<[_data: BytesLike], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "generateKeys"
  ): TypedContractMethod<[_data: BytesLike], [string], "view">;

  getEvent(
    key: "KMSCalled"
  ): TypedContractEvent<
    KMSCalledEvent.InputTuple,
    KMSCalledEvent.OutputTuple,
    KMSCalledEvent.OutputObject
  >;

  filters: {
    "KMSCalled(address,bytes)": TypedContractEvent<
      KMSCalledEvent.InputTuple,
      KMSCalledEvent.OutputTuple,
      KMSCalledEvent.OutputObject
    >;
    KMSCalled: TypedContractEvent<
      KMSCalledEvent.InputTuple,
      KMSCalledEvent.OutputTuple,
      KMSCalledEvent.OutputObject
    >;
  };
}
