/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  MockDecryption,
  MockDecryptionInterface,
} from "../../../contracts/test/MockDecryption";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "requestId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "bytes",
        name: "ciphertext",
        type: "bytes",
      },
      {
        indexed: true,
        internalType: "address",
        name: "requester",
        type: "address",
      },
    ],
    name: "DecryptionProcessed",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_requestId",
        type: "uint256",
      },
    ],
    name: "isRequestProcessed",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_requestId",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "_ciphertext",
        type: "bytes",
      },
      {
        internalType: "address",
        name: "_requester",
        type: "address",
      },
    ],
    name: "processDecryption",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "processedRequests",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561000f575f80fd5b506103158061001d5f395ff3fe608060405234801561000f575f80fd5b506004361061003f575f3560e01c80630deffebf1461004357806339ca2ae01461006a578063e6f0af6e1461008c575b5f80fd5b6100566100513660046101b8565b6100ae565b604051901515815260200160405180910390f35b61005661007836600461027c565b5f9081526020819052604090205460ff1690565b61005661009a36600461027c565b5f6020819052908152604090205460ff1681565b5f8381526020819052604081205460ff16156101225760405162461bcd60e51b815260206004820152602960248201527f4d6f636b44656372797074696f6e3a207265717565737420616c7265616479206044820152681c1c9bd8d95cdcd95960ba1b606482015260840160405180910390fd5b5f8481526020819052604090819020805460ff19166001179055516001600160a01b0383169085907ff594dbc1223914451651160631ffb8e3e8c76dbf144e9a499ce07c477cd8da1790610177908790610293565b60405180910390a35060019392505050565b634e487b7160e01b5f52604160045260245ffd5b80356001600160a01b03811681146101b3575f80fd5b919050565b5f805f606084860312156101ca575f80fd5b83359250602084013567ffffffffffffffff808211156101e8575f80fd5b818601915086601f8301126101fb575f80fd5b81358181111561020d5761020d610189565b604051601f8201601f19908116603f0116810190838211818310171561023557610235610189565b8160405282815289602084870101111561024d575f80fd5b826020860160208301375f6020848301015280965050505050506102736040850161019d565b90509250925092565b5f6020828403121561028c575f80fd5b5035919050565b5f602080835283518060208501525f5b818110156102bf578581018301518582016040015282016102a3565b505f604082860101526040601f19601f830116850101925050509291505056fea2646970667358221220ab487b18559e9e064ddda23f6ae39832c5e541fcabae2e3642c8b7d748e0c88964736f6c63430008180033";

type MockDecryptionConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MockDecryptionConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class MockDecryption__factory extends ContractFactory {
  constructor(...args: MockDecryptionConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      MockDecryption & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): MockDecryption__factory {
    return super.connect(runner) as MockDecryption__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MockDecryptionInterface {
    return new Interface(_abi) as MockDecryptionInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): MockDecryption {
    return new Contract(address, _abi, runner) as unknown as MockDecryption;
  }
}
