/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  MockKMSGeneration,
  MockKMSGenerationInterface,
} from "../../../contracts/test/MockKMSGeneration";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "caller",
        type: "address",
      },
      {
        indexed: false,
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "KMSCalled",
    type: "event",
  },
  {
    stateMutability: "payable",
    type: "fallback",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "_data",
        type: "bytes",
      },
    ],
    name: "generateKeys",
    outputs: [
      {
        internalType: "bytes",
        name: "",
        type: "bytes",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    stateMutability: "payable",
    type: "receive",
  },
] as const;

const _bytecode =
  "0x608060405234801561000f575f80fd5b506102418061001d5f395ff3fe608060405260043610610021575f3560e01c806337c6f59e1461009f57610064565b36610064576040805160208082525f9082015233917f6143579802f5d2609d6025dc5260c0c7f1104791a97f771a7f251d8cfd14dbb891015b60405180910390a2005b336001600160a01b03167f6143579802f5d2609d6025dc5260c0c7f1104791a97f771a7f251d8cfd14dbb85f3660405161005a9291906100d2565b3480156100aa575f80fd5b506100bc6100b9366004610114565b90565b6040516100c991906101bf565b60405180910390f35b60208152816020820152818360408301375f818301604090810191909152601f909201601f19160101919050565b634e487b7160e01b5f52604160045260245ffd5b5f60208284031215610124575f80fd5b813567ffffffffffffffff8082111561013b575f80fd5b818401915084601f83011261014e575f80fd5b81358181111561016057610160610100565b604051601f8201601f19908116603f0116810190838211818310171561018857610188610100565b816040528281528760208487010111156101a0575f80fd5b826020860160208301375f928101602001929092525095945050505050565b5f602080835283518060208501525f5b818110156101eb578581018301518582016040015282016101cf565b505f604082860101526040601f19601f830116850101925050509291505056fea26469706673582212204bec0e7ed10fed50783fa1899699b24577f6635f37358fc3c44f7efbaae0df5164736f6c63430008180033";

type MockKMSGenerationConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MockKMSGenerationConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class MockKMSGeneration__factory extends ContractFactory {
  constructor(...args: MockKMSGenerationConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      MockKMSGeneration & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): MockKMSGeneration__factory {
    return super.connect(runner) as MockKMSGeneration__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MockKMSGenerationInterface {
    return new Interface(_abi) as MockKMSGenerationInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): MockKMSGeneration {
    return new Contract(address, _abi, runner) as unknown as MockKMSGeneration;
  }
}
